# Streamlit 本番環境用設定ファイル
# 各設定項目の詳細説明付き

[server]
# ブラウザを自動で開かない（サーバー環境での実行に適している）
# デフォルト: false
headless = true

# Streamlitアプリが待ち受けるポート番号
# デフォルト: 8501
port = 8501

# サーバーがリッスンするIPアドレス
# "0.0.0.0" で全てのネットワークインターフェースからの接続を許可
# デフォルト: (未設定)
address = "0.0.0.0"

# 静的ファイル配信機能を無効化（セキュリティ向上）
# staticディレクトリからのファイル配信を禁止
# デフォルト: false
enableStaticServing = false

# ファイル変更時の自動再実行を無効化（本番環境では不要）
# 開発環境でのみ有効にすべき機能
# デフォルト: false
runOnSave = false

[browser]
# Streamlitへの使用統計送信を無効化（プライバシー保護）
# 本番環境では通常無効化する
# デフォルト: true
gatherUsageStats = false

# ブラウザが接続すべきサーバーアドレス
# コンテナ環境では "0.0.0.0" を指定
# デフォルト: "localhost"
serverAddress = "0.0.0.0"

# ブラウザが接続すべきポート番号
# server.portと同じ値を設定
# デフォルト: server.portの値
serverPort = 8501

[global]
# 開発モードを無効化（本番環境用の設定）
# 開発者向け機能や詳細なエラー表示を制限
# デフォルト: false
developmentMode = false

# 直接実行時の警告表示を無効化
# "python script.py" での実行時の警告を非表示
# デフォルト: true
showWarningOnDirectExecution = false

[client]
# エラー詳細の表示レベル設定
# "full": 完全なエラー情報を表示（本番環境でも詳細確認のため有効）
# 他の選択肢: "stacktrace", "type", "none"
# デフォルト: "full"
showErrorDetails = "full"

# ツールバーの表示モード設定
# "viewer": 開発者オプションを非表示（本番環境に適している）
# 他の選択肢: "auto", "developer", "minimal"
# デフォルト: "auto"
toolbarMode = "viewer"

# マルチページアプリでのサイドバーナビゲーション表示
# pages/ディレクトリベースのナビゲーションを有効化
# デフォルト: true
showSidebarNavigation = true

[ui]
# Streamlitのトップバーを非表示
# より洗練されたUIを実現（ブランディング向上）
# カスタム設定項目
hideTopBar = true

[theme]
# ダークテーマを適用
# "light" または "dark" から選択可能
# ユーザー体験向上のためのテーマ設定
base = "dark"
