# Use the official Microsoft Python image (Debian Bullseye based)
FROM mcr.microsoft.com/devcontainers/python:1-3.11-bullseye

# Set the working directory
WORKDIR /home/vscode/python

# Install Python packages that are commonly used
RUN pip install --upgrade pip

# Keep the container running
CMD ["sleep", "infinity"]